spring:
  batch:
    job:
      names: ${job.name:NONE}
  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost:9092/~/test
      username: sa
      password:

  sql:
    init:
      mode: always
      data-locations: classpath:person.sql